A=int(input("PLEASE ENTER YOUR PIN:"))
print("*"*50)
print("\t1.cash withdraw1")
print("\t2. Balace Enquiry")
print("\t3. Pin generate")
print("\t4.Mini statement")
print("\t5.Exit")
print("*"*50)
a=int(input("Please select option:"))
match(a):
    case 1:
        A=float(input("PLEASE ENTER WITHDRAWAL AMOUNT"))
        print("-"*50)
        print("\tplease wait your transection getting processing...")
        print("-"*50)
        print(A,"\tYour transection get successful...")
        print("-"*50)
        print("\t Thankyou for visiting....")
    case 2:
        print("\t Your account is empty....")    
        print("\t Please deposite amount")
        print("-"*50)
        print("\t Thankyou for visiting....")
    case 3:
        b=int(input("Please enter acount number"))
        print("-"*50)
        B=int(input("PLEASE ENTER OTP SEN TO YOUR REGISTRATION NUMBER"))
        print("-"*50)
        B=int(input("ENTER YOUR NEW PIN"))
        print("-"*50)
        print=int(input("enter your new pin"))
        print("-"*50)
        print("your pin generated succesfully....")
        print("-"*50) 
        print("Thankyou for visiting....") 
    case 4:
        print("\tYou don't have any transection")
        print("-"*50) 
        print("\tThankyou for visiting")
    case 5:
        print("Thankyou for visiting")